name: 'Build Site'
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./build-site.sh
      - name: Upload Release Artifact
        id: upload
        uses: softprops/action-gh-release@v1
        with:
          files: site.tar.gz
      - name: Webhook
        uses: joelwmale/webhook-action@2.3.2
        with:
          #${{ secrets.WEBHOOK_URL }}
          url: https://bessems.org/test.php
          body: '{"file": "${{ steps.upload.outputs.url }}/site.tar.gz"", "release": "${{github.ref}}"}'
      # - name: Upload Build Artifats
        # uses: actions/upload-artifact@v3
        # with:
        #   name: site
        #   path: ${{ github.workspace }}/build/html
      # Should add webhook notifying hosting server to pull artifact.